name: "CodeQL: 0x1abin/MultiButton"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: 0x1abin/MultiButton
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || '0x1abin/MultiButton' }}
      ref: ${{ inputs.ref }}
      build_script: '0x1abin_MultiButton.sh'
      install_arm-none-eabi-gcc: false
