name: "CodeQL: alrevuelta/cONNXr"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: alrevuelta/cONNXr
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'alrevuelta/cONNXr' }}
      ref: ${{ inputs.ref }}
      build_script: 'alrevuelta_cONNXr.sh'
      install_arm-none-eabi-gcc: false
