name: "CodeQL: aws/aws-iot-device-sdk-embedded-C"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '20 7 * * 6'

jobs:
  call-codeql-workflow:
    uses: ./.github/workflows/codeql.yml
    with:
      repository: aws/aws-iot-device-sdk-embedded-C
      build_script: aws-iot-device-sdk-embedded-C.sh
