name: "CodeQL: aws/aws-iot-device-sdk-embedded-C"

on:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: aws/aws-iot-device-sdk-embedded-C
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
    with:
      repository: ${{ inputs.repository || 'aws/aws-iot-device-sdk-embedded-C' }}
      ref: ${{ inputs.ref }}
      build_script: aws_aws-iot-device-sdk-embedded-C.sh
