name: "CodeQL: azure-rtos/threadx"

on:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: azure-rtos/threadx
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
    with:
      repository: ${{ inputs.repository || 'azure-rtos/threadx' }}
      ref: ${{ inputs.ref }}
      build_script: 'azure-rtos_threadx.sh'
      install_arm_cross_compiler: true
