name: "CodeQL: Azure/azure-iot-sdk-c"

on:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: Azure/azure-iot-sdk-c
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
    with:
      repository: ${{ inputs.repository || 'Azure/azure-iot-sdk-c' }}
      ref: ${{ inputs.ref }}
      build_script: Azure_azure-iot-sdk-c.sh
