name: "CodeQL: azure-rtos/getting-started"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: azure-rtos/getting-started
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql-cli.yml
    with:
      repository: ${{ inputs.repository || 'azure-rtos/getting-started' }}
      ref: ${{ inputs.ref }}
      build_script: 'azure-rtos_getting-started.sh'
      install_arm_cross_compiler: true
