name: "CodeQL: bacnet-stack/bacnet-stack"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: bacnet-stack/bacnet-stack
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'bacnet-stack/bacnet-stack' }}
      ref: ${{ inputs.ref }}
      build_script: 'bacnet-stack_bacnet-stack.sh'
      install_arm-none-eabi-gcc: false
