name: "CodeQL: coder-mike/microvium"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: coder-mike/microvium
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'coder-mike/microvium' }}
      ref: ${{ inputs.ref }}
      build_script: 'coder-mike-microvium.sh'
      install_arm-none-eabi-gcc: false
