name: "CodeQL: eclipse/paho.mqtt.embedded-c"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: eclipse/paho.mqtt.embedded-c
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'eclipse/paho.mqtt.embedded-c' }}
      ref: ${{ inputs.ref }}
      build_script: 'eclipse_paho.mqtt.embedded-c.sh'
      install_arm-none-eabi-gcc: false
