name: "CodeQL: IVOES/juliet-test-suite-for-c-cplusplus-v1-3"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: IVOES/juliet-test-suite-for-c-cplusplus-v1-3
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'IVOES/juliet-test-suite-for-c-cplusplus-v1-3' }}
      ref: ${{ inputs.ref }}
      build_script: 'IVOES_juliet-test-suite-for-c-cplusplus-v1-3.sh'
      install_arm-none-eabi-gcc: false
