name: "CodeQL: IVOES/zephyrproject"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: IVOES/zephyrproject
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'IVOES/zephyrproject' }}
      ref: ${{ inputs.ref }}
      build_script: 'IVOES_zephyrproject.sh'
      install_arm-none-eabi-gcc: false
      sarif_filter_patterns: '-modules/**'
