name: "CodeQL: jedisct1/libhydrogen"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: jedisct1/libhydrogen
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'jedisct1/libhydrogen' }}
      ref: ${{ inputs.ref }}
      build_script: 'jedisct1-libhydrogen.sh'
      install_arm-none-eabi-gcc: false
