name: "CodeQL: kgoba/ft8_lib"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: kgoba/ft8_lib
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'kgoba/ft8_lib' }}
      ref: ${{ inputs.ref }}
      build_script: 'kgoba-ft8_lib.sh'
      install_arm-none-eabi-gcc: false
