name: "CodeQL: layumi/2016_person_re-ID"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: layumi/2016_person_re-ID
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'layumi/2016_person_re-ID' }}
      ref: ${{ inputs.ref }}
      build_script: 'layumi_2016_person_re-ID.sh'
      install_arm-none-eabi-gcc: false
