name: "CodeQL: lmarzen/esp32-weather-epd"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: lmarzen/esp32-weather-epd
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'lmarzen/esp32-weather-epd' }}
      ref: ${{ inputs.ref }}
      build_script: 'lmarzen_esp32-weather-epd.sh'
      install_arm-none-eabi-gcc: false
