name: "CodeQL: never-lang/never"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: never-lang/never
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'never-lang/never' }}
      ref: ${{ inputs.ref }}
      build_script: 'never-lang-never.sh'
      install_arm-none-eabi-gcc: false
