name: "CodeQL: paladin-t/my_basic"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: paladin-t/my_basic
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'paladin-t/my_basic' }}
      ref: ${{ inputs.ref }}
      build_script: 'paladin-t_my_basic.sh'
      install_arm-none-eabi-gcc: false
