name: "CodeQL: raysan5/raylib"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: raysan5/raylib
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'raysan5/raylib' }}
      ref: ${{ inputs.ref }}
      build_script: 'raysan5-raylib.sh'
      install_arm_cross_compiler: false
