name: "CodeQL: rryqszq4/ngx-php"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: rryqszq4/ngx-php
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'rryqszq4/ngx-php' }}
      ref: ${{ inputs.ref }}
      build_script: 'rryqszq4-ngx-php.sh'
      install_arm-none-eabi-gcc: false
