name: "[rust4embedded] CodeQL: RT-Thread/rt-thread"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: RT-Thread/rt-thread
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    # uses: ./.github/workflows/codeql-cli-rust4embedded.yml
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'RT-Thread/rt-thread' }}
      ref: ${{ inputs.ref }}
      build_script: 'RT-Thread-rt-thread.sh'
      install_arm-none-eabi-gcc: true
