name: "CodeQL: someone42/hardware-bitcoin-wallet"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to run CodeQL on. Format: owner/repo.'
        required: true
        type: string
        default: someone42/hardware-bitcoin-wallet
      ref:
        description: 'The branch, tag or SHA to checkout. Default: default branch.'
        required: false
        type: string

jobs:
  call_codeql_workflow:
    uses: ./.github/workflows/codeql-cli.yml
    secrets: inherit
    with:
      repository: ${{ inputs.repository || 'someone42/hardware-bitcoin-wallet' }}
      ref: ${{ inputs.ref }}
      build_script: 'someone42_hardware-bitcoin-wallet.sh'
      install_arm-none-eabi-gcc: false
