name: "Test self-hosted runner"

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: self-hosted

    steps:
    - name: Run command
      run: |
        lsb_release -a
        whoami
        codeql --version || true

    - name: Test push-to-another-repo
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      run: |
        echo $SSH_DEPLOY_KEY
