name: "Test self-hosted runner"

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: self-hosted

    steps:
    - name: Run command
      run: |
        lsb_release -a
        whoami
        codeql --version || true
